model:
  resume: False
  amp: True
  base_learning_rate: 2.0e-5
  params:
    embed_dim: 4
    label_conc: 10
    lossconfig:
      params:
        disc_start: 100000000

    ddconfig:
      double_z: False
      channels: 128
      resolution: 128
      timesteps: 16
      skip: 1
      in_channels: 1
      out_ch: 1
      num_res_blocks: 1 # num_res_blocks: 2
      attn_resolutions: []
      splits: 1
      label_conc: 10
